package hackfest.pheonix.haptiq.Activities;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import com.github.nkzawa.emitter.Emitter;
import com.github.nkzawa.socketio.client.IO;
import com.github.nkzawa.socketio.client.Socket;
import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import org.json.JSONException;
import org.json.JSONObject;

import java.net.URISyntaxException;
import java.util.HashMap;

import hackfest.pheonix.haptiq.Constants;
import hackfest.pheonix.haptiq.R;

public class MainActivity extends AppCompatActivity {

    Button scanCode, fingerprint;
    IntentIntegrator intentIntegrator;
    private Socket mSocket;
    SharedPreferences sharedPreferences;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        sharedPreferences = getSharedPreferences(Constants.PREF_IDS, MODE_PRIVATE);
        //Connect to socket and get id
        try {
            mSocket = IO.socket(Constants.SOCKET_IP);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        mSocket.connect();

        String socketId = sharedPreferences.getString(Constants.SOCKET_ID, "");
        if (socketId.isEmpty()) {
            //First time pairing
            mSocket.emit("phone-join");
            mSocket.on("join-with", new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.e("demo", args[0].toString() + " length " + args[0].toString().length());
                    sharedPreferences.edit().putString(Constants.SOCKET_ID, args[0].toString()).apply();
                }
            });
        }

        scanCode = (Button) findViewById(R.id.scanCode);
        fingerprint = (Button) findViewById(R.id.fingerprint);
        intentIntegrator = new IntentIntegrator(this);
        scanCode.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                intentIntegrator.initiateScan();
            }
        });

        fingerprint.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                startActivity(new Intent(MainActivity.this, Fingerprint.class));
            }
        });
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        // Handle activity result generated by QR code scanning
        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if (result != null) {
            //if QRcode has nothing in it
            if (result.getContents() == null) {
                Toast.makeText(this, "Result Not Found. Scan again", Toast.LENGTH_LONG).show();
            } else {
                String qrCodeResult = result.getContents();
                Log.e("demo","QR read result "+qrCodeResult);
                try {
                    JSONObject object = new JSONObject(qrCodeResult);
                    sharedPreferences.edit().putString(Constants.CHROME_EXTENSION_ID,object.optString(Constants.CHROME_EXTENSION_ID)).apply();
                    sharedPreferences.edit().putString(Constants.SECRET_KEY,object.optString(Constants.SECRET_KEY)).apply();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                HashMap<String, String> socketPairingData = new HashMap<>();
                socketPairingData.put(Constants.CHROME_EXTENSION_ID, sharedPreferences.getString(Constants.CHROME_EXTENSION_ID, ""));
                socketPairingData.put(Constants.SOCKET_ID, sharedPreferences.getString(Constants.SOCKET_ID, ""));
                socketPairingData.put(Constants.FCM_ID, sharedPreferences.getString(Constants.FCM_ID, ""));
                JSONObject jsonObject = new JSONObject(socketPairingData);
                Log.e("demo", jsonObject.toString());
                // Send request for pairing
                mSocket.emit("pairing", jsonObject);
                sharedPreferences.edit().putString(Constants.CHROME_EXTENSION_ID, qrCodeResult).apply();
                startActivity(new Intent(MainActivity.this, AccessCredential.class));
                finish();
            }
        } else {
            super.onActivityResult(requestCode, resultCode, data);
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        mSocket.disconnect();
        mSocket.off();
    }
}
